[bison]
DownloadUrlTemplate = "https://ftpmirror.gnu.org/bison/{{ .Filename }}"
FilenameTemplate = "bison-{{ .Version }}.tar.xz"
PreferredVersion = "3.8.2"

[bison.files."bison-3.8.2.tar.xz"]
SHA-256 = "9bba0214ccf7f1079c5d59210045227bcf619519840ebfa80cd3849cff5a5bf2"
Size = 2817324

[tinygo]
DownloadUrlTemplate = "https://github.com/tinygo-org/tinygo/releases/download/v{{ .Version }}/{{ .Filename }}"
FilenameTemplate = "tinygo{{ .Version }}.linux-{{ .Arch }}.tar.gz"
PreferredVersion = "0.35.0"

[tinygo.files."tinygo0.35.0.linux-amd64.tar.gz"]
SHA-256 = "a6d25bec05e2ee3534ffcda3cb717336a6f4e81e4821296bff7da2fe71bf1678"
Size = 148831863

[tinygo.files."tinygo0.35.0.linux-arm64.tar.gz"]
SHA-256 = "1fcf322942b5a293079af36cdfac29d545fcd341541424de82a05225b6c77803"
Size = 146601071
